# site settings
title:       cvless
tagline:     Jekyll theme for a beautiful online CV
url:         https://cvless.netlify.app
baseurl:     ""
permalink:   pretty
version:     2.0.0

# user settings
author:
  name:      Place Holder
  url:       https://username.github.io
  email:     username@domain.com

# build settings
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - .git
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
sass:
  sass_dir:  _sass
  style:     :compressed
  sourcemap: never
feed:
  path:      atom.xml
autopages:
  enabled: false
pagination:
  enabled:   true
  per_page:  1
  sort_reverse: true
  permalink: /blog/:num/
  title:     ":title &middot; :num"
