# seo tags
title:        cvless
description:  Jekyll theme for a beautiful online CV

# personal info
firstname:    Place
lastname:     Holder
photo:        assets/photo.jpg
organization: University of Jekyll
department:   Department of Themes
address:      123 Main St, Anytown, USA
office:       Foobar Hall 1.23
phone:        +1 234 567 890

# navigation
navtext:      readme
navlink:      https://github.com/piazzai/cvless/blob/master/README.md

# cv pdf
#cv:           cv.pdf

# footer buttons
email:        username@domain.com
scholar:      https://scholar.google.com/citations?user=xxxxxxxxxxxx
orcid:        https://orcid.org/0000-0000-0000-0000
#lichess:     username
github:       username

# tracking id
analytics:    XX-000000000-0

# repository
repo:         https://github.com/username/username.github.io

# ruby gems
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
